extends SceneTree

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var owner := Node3D.new()
	root.add_child(owner)
	var motivation=load("res://scripts/exploration_motivation.gd").new()
	root.add_child(motivation)
	motivation.setup(owner)
	var first: Dictionary=motivation.record("ember_bloom",Vector3(12,0,0),"day")
	assert(first.scrap==0 and not first.has("memory"),"First route item keeps its base reward")
	var second: Dictionary=motivation.record("memory_crystal",Vector3(12,0,0),"day")
	assert(second.scrap==4 and not second.has("memory") and motivation.streak==2,"Two different discoveries create a route streak")
	var third: Dictionary=motivation.record("supply_cache",Vector3(12,0,0),"day")
	assert(third.scrap==18 and not third.has("memory") and motivation.best_streak==3,"Three-item route pays the mid bonus")
	motivation.set_waylight_count(2)
	var fourth: Dictionary=motivation.record("waylight",Vector3(50,0,0),"night")
	assert(fourth.scrap==69 and not fourth.has("memory"),"Full set and deep route bonuses are paid once")
	assert(motivation.night_discoveries==1 and motivation.deep_discoveries==1)
	assert(motivation.route_text().contains("完整搜寻"))
	var repeat: Dictionary=motivation.record("waylight",Vector3(12,0,0),"day")
	assert(repeat.scrap==0 and not repeat.has("memory"),"Repeating a type does not replay the full set reward")
	var network: Dictionary=motivation.record("ember_bloom",Vector3(12,0,0),"day")
	assert(network.scrap==6 and not network.has("memory"),"A two-lantern network adds a small route bonus")
	assert(motivation.run_summary().contains("最长连段 4"))
	motivation.set_waylight_count(0)
	motivation.arm_contract_affinity(["ember_bloom"])
	var affinity: Dictionary=motivation.record("ember_bloom",Vector3(12,0,0),"day")
	assert(affinity.scrap==8 and not affinity.has("memory") and not motivation.affinity_active(),"A matched contract affinity pays once and is consumed")
	var no_repeat: Dictionary=motivation.record("ember_bloom",Vector3(12,0,0),"day")
	assert(no_repeat.scrap==0 and not no_repeat.has("memory"),"Consumed contract affinity must not repeat on later discoveries")
	assert(motivation.route_summary().contains("路线完成 4/4"),"Run recap must report all four discovered route types")
	print("EXPLORATION_MOTIVATION_OK route streak, full set, deep/night risk, light network and recap")
	owner.queue_free();motivation.queue_free()
	await process_frame
	quit()
