extends SceneTree
## Real F and 4/5/6 regressions for commitment before contract work.
## Offers and sources are generated by the production scene, never fake completions.
const Contracts := preload("res://scripts/day_contracts.gd")
const HOME := Vector3(0, 5, 3.1)
const STEP := .05
var game: Node3D
var failures: Array[String] = []
var checks := 0
var render_test := false
var evidence: Array[Dictionary] = []

func _initialize() -> void:
	if DisplayServer.get_name() != "headless":
		DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_NO_FOCUS, true)
		root.size = Vector2i(1920, 1200)
		root.content_scale_mode = Window.CONTENT_SCALE_MODE_VIEWPORT
		root.content_scale_size = Vector2i(1920, 1200)
		root.hide()
	render_test = "--render-test" in OS.get_cmdline_user_args()
	call_deferred("run")

func check(condition: bool, message: String) -> void:
	checks += 1
	if condition: return
	failures.append(message)
	if failures.size() <= 24: push_error(message)

func press(code: int) -> void:
	var event := InputEventKey.new()
	event.keycode = code
	event.pressed = true
	game._unhandled_input(event)
	event.pressed = false
	game._unhandled_input(event)

func clear_enemies() -> void:
	for enemy in game.enemies:
		if is_instance_valid(enemy): enemy.queue_free()
	game.enemies.clear()

func hunters() -> int:
	var count := 0
	for enemy in game.enemies:
		if is_instance_valid(enemy) and enemy.get_meta("contract_hunter", false): count += 1
	return count

func put_hero(point: Vector3) -> void:
	point.y = game.outpost_height(point)
	game.hero.position = point
	game.hero_path.clear()
	game.move_goal = point

func clear_optional(point: Vector3) -> void:
	# F has several legitimate actions. Silence only unrelated nearby fixtures;
	# contract sources, exploration rewards and expedition states stay real.
	for item: Dictionary in game.discoveries.items:
		if item.position.distance_to(point) < 5.0:
			item.state = "cooling"
			item.respawn = 100.0
			item.node.visible = false
	for animal: Dictionary in game.wildlife.animals:
		if animal.position.distance_to(point) < 5.0:
			animal.state = "cooldown"
			animal.node.visible = false
			animal.label.visible = false

func seed_for(wanted: String, index: int) -> int:
	var old_phase: String = game.phase
	var old_day: int = game.day_number
	game.phase = "day"
	game.day_number = 2
	var probe := Contracts.new()
	game.add_child(probe)
	var found := -1
	for seed_value in 512:
		probe.setup(game, seed_value)
		probe.on_day()
		if probe.offers.size() > index and String(probe.offers[index].kind) == wanted:
			found = seed_value
			break
	probe.queue_free()
	game.phase = old_phase
	game.day_number = old_day
	return found

func boot_day(wanted: String, index: int = 2) -> bool:
	game = load("res://scenes/nightfall.tscn").instantiate()
	root.add_child(game)
	current_scene = game
	await process_frame
	game.set_process(false)
	game.world.set_process(false)
	press(KEY_1)
	check(game.phase == "night", "The actual opening key must enter the first night")
	clear_enemies()
	var seed_value := seed_for(wanted, index)
	check(seed_value >= 0, "A production seed must expose %s at offer %d" % [wanted, index])
	if seed_value < 0: return false
	game.run.seed_value = seed_value
	game.contracts.setup(game, seed_value)
	game.finish_night()
	check(game.phase == "draft" and game.day_number == 2, "The real first night must reach dawn")
	press(KEY_1)
	check(game.phase == "day" and game.contracts.status == "active", "The real dawn key must start a day and generate offers")
	clear_enemies()
	game.hero.attack_timer = 999.0
	game.pulse_timer = 999.0
	put_hero(HOME)
	check(game.contracts.selected_offer == 0 and game.contracts.offers.size() == 3,
		"The day must keep the default safe offer before ordinary exploration")
	check(String(game.contracts.offers[index].kind) == wanted, "The wanted real offer must survive night-to-dawn generation")
	return game.phase == "day" and game.contracts.offers.size() > index and String(game.contracts.offers[index].kind) == wanted

func close_game() -> void:
	if not is_instance_valid(game): return
	await game.prepare_shutdown()
	game.queue_free()
	await process_frame
	await create_timer(.5).timeout

func advance(seconds: float) -> void:
	var steps := ceili(seconds / STEP)
	for step in steps:
		game.simulate(minf(STEP, seconds - float(step) * STEP))

func state_snapshot() -> Dictionary:
	var sources: Array[Dictionary] = []
	for target: Dictionary in game.contracts.targets:
		sources.append({"index": int(target.index), "source": target.source})
	var action_states: Array[Dictionary] = []
	for offer: Dictionary in game.contracts.offers:
		for target: Dictionary in offer.targets:
			var source: Dictionary = target.source
			action_states.append({"kind": String(offer.kind), "index": int(target.index),
				"state": source.get("state", ""), "progress": source.get("progress", 0.0),
				"collected": source.get("collected", false), "cleansed": source.get("cleansed", false),
				"respawn": source.get("respawn", 0.0)})
	return {"offer": game.contracts.selected_offer, "kind": game.contracts.kind,
		"reward": game.contracts.selected_reward.duplicate(true), "sources": sources,
		"scrap": game.scrap, "memory": game.essence, "hunters": hunters(),
		"enemy_count": game.enemies.size(), "risk": game.contracts.risk_spawned,
		"risk_count": game.contracts.risk_spawn_count, "done": game.contracts.done.duplicate(true),
		"touched": game.contracts.offer_touched.duplicate(true), "notified": game.contracts.start_notified,
		"started": game.contracts.progress_started, "pending": game.contracts.pending_reward.duplicate(true),
		"action_states": action_states, "clock": game.phase_time, "notice": game.notice}

func assert_read_only_queries(index: int, expected_available: bool, label: String) -> void:
	var before := state_snapshot()
	for repeat in 5:
		var choice: Dictionary = game.contracts.offer_choice_state(index)
		var estimate: Dictionary = game.contracts.primary_budget(index)
		var hint: String = game.contracts.choice_hint()
		check(bool(choice.available) == expected_available, "%s: a read-only choice query must reflect live eligibility" % label)
		if index != game.contracts.selected_offer and not expected_available:
			check(not estimate.available and estimate.risk == "unavailable_offer",
				"%s: an explored unselected offer must refuse a usable route estimate" % label)
		else:
			check(bool(estimate.available) == expected_available,
				"%s: the selected unfinished route must retain its real estimate" % label)
		check(not hint.is_empty(), "%s: the real hint query must expose choice state" % label)
	check(state_snapshot() == before, "%s: repeated choice, budget and hint queries must not touch sources, history, rewards or hunters" % label)

func assert_rejected(index: int, label: String, reason_terms: Array[String] = ["已探索", "已开始", "先选", "不可"]) -> void:
	var before := state_snapshot()
	press(KEY_4 + index)
	var after := state_snapshot()
	var unchanged: bool = after.offer == before.offer and after.kind == before.kind and after.reward == before.reward
	check(unchanged, "%s: selecting preworked sources must preserve the current offer and payout" % label)
	check(after.sources.size() == before.sources.size(), "%s: rejection must preserve the target count" % label)
	for target_index in mini(after.sources.size(), before.sources.size()):
		check(after.sources[target_index].index == before.sources[target_index].index and
			is_same(after.sources[target_index].source, before.sources[target_index].source),
			"%s: rejection must retain the live source identity" % label)
	check(after.scrap == before.scrap and after.memory == before.memory and after.done == before.done,
		"%s: rejected input must not pay, consume or claim progress" % label)
	check(after.hunters == before.hunters and after.enemy_count == before.enemy_count and
		after.risk == before.risk and after.risk_count == before.risk_count,
		"%s: rejected input must not spawn or alter contract hunters" % label)
	var reason_visible := false
	for term: String in reason_terms:
		if term in game.notice: reason_visible = true
	check(reason_visible, "%s: the actual input must explain why the offer cannot be accepted" % label)
	evidence.append({"case": label, "before_offer": before.offer, "after_offer": after.offer,
		"unchanged": unchanged, "notice": game.notice, "hunters": after.hunters})
	# On an unfixed baseline, recover through real input so the next state of the
	# same source is a fresh counterexample rather than a contaminated assertion.
	if after.offer != before.offer: press(KEY_4 + int(before.offer))

func capture(name: String) -> void:
	assert_active_hud_width(name)
	if not render_test: return
	if DisplayServer.get_name() == "headless":
		check(false, "--render-test requires a real rendering backend")
		return
	game.world.night_mix = 0.0
	game.world.apply_lighting()
	game.camera.size = 31.0
	game.camera.position = game.hero.position + Vector3(0, 25, 29)
	game.camera.look_at(game.hero.position)
	game.hud.queue_redraw()
	await process_frame
	await RenderingServer.frame_post_draw
	var rendered: Image = root.get_texture().get_image()
	check(rendered.get_size() == Vector2i(1920, 1200), "%s: the real HUD must render at 1920x1200" % name)
	check(rendered.save_png("res://build/contract-prework-%s.png" % name) == OK,
		"%s: the actual refusal HUD must save" % name)

func assert_active_hud_width(label: String) -> void:
	var contract: Node = game.contracts
	if game.phase != "day" or contract.status != "active": return
	var budget: Dictionary = contract.primary_budget()
	var title: String = contract.TITLES.get(contract.kind, "自由探索")
	var rows: Array[Dictionary] = [
		{"text": "可选委托 · %s · 方案%d/%d · %d/%d" % [title, contract.selected_offer + 1,
			contract.offers.size(), contract.done.size(), contract.targets.size()], "size": 19},
		{"text": contract.primary_travel_text(budget), "size": 14},
		{"text": contract.primary_timing_text(budget), "size": 12},
		{"text": contract.offer_summary(contract.selected_offer), "size": 11},
		{"text": "P指路/F行动 · " + contract.choice_hint() + " · " + contract.primary_condition_text(budget), "size": 11}]
	for row: Dictionary in rows:
		var width: float = game.hud.font.get_string_size(String(row.text), HORIZONTAL_ALIGNMENT_LEFT, -1, int(row.size)).x
		check(width <= 530.0, "%s: the actual %dpx active HUD row must fit its 530px content area (%.1fpx): %s" %
			[label, int(row.size), width, String(row.text)])

func generator_case() -> void:
	if not await boot_day("generator"): await close_game(); return
	var target: Dictionary = game.contracts.offers[2].targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	press(KEY_F)
	check(source.state == "active" and source.progress == 0.0, "Ordinary F must really start the unselected generator")
	check(not game.contracts.progress_started and hunters() == 0, "An unselected generator must not lock the unrelated safe offer or charge extra risk")
	assert_read_only_queries(2, false, "unselected-generator-started")
	assert_rejected(2, "generator-start-same-frame")
	clear_enemies()
	await process_frame
	advance(6.0)
	check(source.state == "active" and is_equal_approx(float(source.progress), 6.0), "The real hold-circle simulation must accumulate half the generator work")
	assert_rejected(2, "generator-half-work")
	advance(6.1)
	check(source.state == "complete" and game.generator_cells == 1, "The real cleared hold-circle must award a completed energy cell")
	assert_rejected(2, "generator-completed")
	await capture("generator")
	await close_game()

func escort_case() -> void:
	if not await boot_day("escort"): await close_game(); return
	var target: Dictionary = game.contracts.offers[2].targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	press(KEY_F)
	check(source.state == "escort", "Ordinary F must recruit the real unselected scout")
	check(not game.contracts.progress_started and hunters() == 0, "An unrelated recruitment must keep the untouched safe offer switchable")
	assert_rejected(2, "escort-start-same-frame")
	clear_enemies()
	game.plan_hero_path(HOME)
	check(not game.hero_path.is_empty(), "The actual hero route must lead the follower through the south gate")
	var elapsed := 0.0
	while source.state == "escort" and game.phase == "day" and elapsed < 45.0:
		game.simulate(STEP)
		elapsed += STEP
	check(source.state == "delivered" and game.survivors_rescued == 1,
		"The actual follower movement and home-area check must deliver the scout")
	assert_rejected(2, "escort-delivered")
	await capture("escort")
	await close_game()

func salvage_case() -> void:
	if not await boot_day("salvage"): await close_game(); return
	var target: Dictionary = game.contracts.offers[2].targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	check(game.expeditions.interaction_prompt().is_empty(), "The real salvage source must be outside expedition interaction ranges")
	var initial_scrap: int = game.scrap
	press(KEY_F)
	check(source.collected and game.scrap > initial_scrap, "Ordinary F must really collect and pay for the unselected salvage source")
	check(not game.contracts.progress_started and hunters() == 0, "Ordinary salvage must not lock the unrelated selected route")
	assert_rejected(2, "salvage-one-of-pair")
	advance(float(game.SALVAGE_REFRESH) + .1)
	check(not source.collected and source.node.visible, "The production refresh loop must actually restore the collected cache after 55 seconds")
	check(game.phase == "day" and game.phase_time > 16.0, "The refreshed-source refusal must happen before the high-risk deadline")
	assert_rejected(2, "salvage-refreshed-history")
	assert_read_only_queries(2, false, "salvage-sticky-after-refresh")
	await capture("salvage-refresh")
	check(not game.contracts.offer_touched.is_empty(), "The ordinary collection must really leave day-local sticky history")
	game.start_night()
	game.finish_night()
	check(game.phase == "draft" and game.day_number == 3, "The real second-night completion must reach the next dawn")
	press(KEY_1)
	check(game.phase == "day" and game.contracts.day_id == 3 and game.contracts.status == "active",
		"The real next-dawn input must generate a fresh daytime offer set")
	check(game.contracts.offer_touched.is_empty() and not game.contracts.start_notified and not game.contracts.progress_started and
		not game.contracts.risk_spawned and game.contracts.risk_spawn_count == 0 and game.contracts.offer_rejection_reason.is_empty(),
		"New-day generation must clear all old touched, first-action, rejection and risk state")
	var refreshed_source_eligible := false
	for candidate: Dictionary in game.contracts.candidates():
		if candidate.kind != "salvage": continue
		for fresh_target: Dictionary in candidate.targets:
			if is_same(fresh_target.source, source): refreshed_source_eligible = true
	check(refreshed_source_eligible, "The actual previously refreshed source must regain candidate eligibility on the next day")
	for index in game.contracts.offers.size():
		press(KEY_4 + index)
		check(game.contracts.selected_offer == index and hunters() == 0, "Fresh-day untouched routes must again accept actual risk keys without immediate hunters")
	await close_game()
	if not await boot_day("salvage"): await close_game(); return
	check(game.contracts.offer_touched.is_empty() and not game.contracts.start_notified and not game.contracts.progress_started and
		not game.contracts.risk_spawned and game.contracts.offer_rejection_reason.is_empty(),
		"A real newly instantiated game and setup must not inherit the old day's commitment state")
	await close_game()

func nest_case() -> void:
	if not await boot_day("nest"): await close_game(); return
	var target: Dictionary = game.contracts.offers[2].targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	check(game.expeditions.interaction_prompt().is_empty() and game.nearest_salvage() == -1,
		"The real nest F must be free of a closer expedition or salvage action")
	var initial_scrap: int = game.scrap
	press(KEY_F)
	check(source.cleansed and game.scrap == initial_scrap + 90, "Ordinary F must seal the real unguarded nest and grant its original reward")
	check(not game.contracts.progress_started and hunters() == 0, "Sealing an unselected nest must not lock the untouched safe offer")
	assert_rejected(2, "nest-sealed-same-frame")
	await capture("nest")
	await close_game()

func unrelated_case() -> void:
	if not await boot_day("generator", 1): await close_game(); return
	var flower: Dictionary = {}
	for item: Dictionary in game.discoveries.items:
		if item.kind != "ember_bloom" or item.state != "ready": continue
		put_hero(item.position)
		if game.contracts.active_target_interaction().is_empty() and game.expeditions.interaction_prompt().is_empty():
			flower = item
			break
	check(not flower.is_empty(), "A real unrelated flower must be available without replacing a contract source")
	if not flower.is_empty():
		press(KEY_F)
		check(flower.state == "cooling", "Ordinary F must actually collect the unrelated flower")
		check(not game.contracts.progress_started, "Unrelated exploration must not lock every offer")
		press(KEY_5)
		check(game.contracts.selected_offer == 1 and game.contracts.kind == "generator",
			"Actual 5 input must still accept an untouched route after unrelated exploration")
		press(KEY_6)
		check(game.contracts.selected_offer == 2, "Actual 6 input must still allow another untouched route")
		press(KEY_4)
		check(game.contracts.selected_offer == 0 and hunters() == 0, "Actual 4 input must return to the untouched safe route without spawning hunters")
	await close_game()

func legal_risk_case(index: int) -> void:
	if not await boot_day("generator", index): await close_game(); return
	press(KEY_4 + index)
	check(game.contracts.selected_offer == index, "The real risk key must accept an untouched generator offer")
	var target: Dictionary = game.contracts.targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	press(KEY_F)
	check(source.state == "active" and game.contracts.progress_started, "Selected-generator F must commit the route at the actual first action")
	check(game.contracts.risk_spawned and game.contracts.risk_spawn_count == index and hunters() == index,
		"The first selected F must synchronously create exactly the advertised 0/1/2 hunters")
	assert_read_only_queries(index, true, "selected-generator-in-progress-%d" % index)
	var enemy_count: int = game.enemies.size()
	press(KEY_F)
	check(hunters() == index and game.enemies.size() == enemy_count, "Repeated real F must never duplicate the selected risk or expedition ambush")
	press(KEY_4 + (index + 1) % 3)
	check(game.contracts.selected_offer == index, "A selected route must reject switching as soon as real work starts")
	if index == 2: await capture("locked")
	press(KEY_ESCAPE)
	var pause_progress: float = source.progress
	var pause_clock: float = game.phase_time
	advance(1.0)
	press(KEY_6)
	check(game.phase == "paused" and source.progress == pause_progress and game.phase_time == pause_clock and hunters() == index,
		"Pause and input must freeze work, clock and contract risk")
	press(KEY_ESCAPE)
	clear_enemies()
	await process_frame
	advance(12.1)
	check(source.state == "complete" and game.contracts.status == "bonus_offer" and game.contracts.risk_spawned,
		"Real committed completion must offer the optional detour after the risk was already paid")
	press(KEY_4)
	check(game.contracts.status == "returning", "The actual return key must preserve the completed primary reward")
	var initial_scrap: int = game.scrap
	game.start_night()
	check(hunters() == 0 and game.phase == "night", "Real dusk must clean up contract hunters")
	check(game.scrap == initial_scrap + int(game.contracts.selected_reward.scrap),
		"Dusk must settle the committed primary payout once without optional bonus")
	game.settle_contract_reward()
	check(game.scrap == initial_scrap + int(game.contracts.selected_reward.scrap), "Repeated settlement must not pay the primary reward twice")
	await close_game()

func deadline_case() -> void:
	if not await boot_day("generator", 2): await close_game(); return
	game.phase_time = 16.0
	assert_rejected(2, "risk-deadline-same-frame", ["截止", "时间", "过期", "不可"])
	check(game.contracts.status == "active" and game.contracts.selected_offer == 0,
		"An expired optional risk must keep the untouched safe route active")
	await capture("deadline")
	await close_game()

func expired_free_exploration_case() -> void:
	if not await boot_day("generator", 2): await close_game(); return
	press(KEY_6)
	var target: Dictionary = game.contracts.targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	game.phase_time = 16.0
	var initial_scrap: int = game.scrap
	press(KEY_F)
	check(source.state == "active", "An expired selected contract must still allow the original generator F action")
	check(game.contracts.status == "expired" and not game.contracts.risk_spawned and hunters() == 0,
		"The actual F at the selected deadline must expire the optional contract without adding risk")
	check(game.enemies.size() == 3, "Expired free exploration must keep exactly the original generator ambush")
	clear_enemies()
	await process_frame
	advance(12.1)
	check(source.state == "complete" and game.scrap == initial_scrap + int(game.expeditions.GENERATOR_REWARD),
		"Expired exploration must retain the real generator completion and original payout")
	check(game.contracts.status == "expired" and game.contracts.pending_reward.is_empty(),
		"Free completion after the optional deadline must not request a high-risk contract reward")
	game.start_night()
	check(game.scrap == initial_scrap + int(game.expeditions.GENERATOR_REWARD) and hunters() == 0,
		"Dusk must not pay an expired optional contract or create extra hunters")
	await close_game()

func salvage_committed_pair_case() -> void:
	if not await boot_day("salvage", 2): await close_game(); return
	press(KEY_6)
	check(game.contracts.targets.size() == 2, "The real salvage offer must require its authored pair of sources")
	for target_index in game.contracts.targets.size():
		var target: Dictionary = game.contracts.targets[target_index]
		put_hero(target.position)
		clear_optional(target.position)
		press(KEY_F)
		check(target.source.collected and game.contracts.done.size() == target_index + 1,
			"Each real selected salvage F must claim its own live source once")
		check(game.contracts.risk_spawned and game.contracts.start_notified and game.contracts.risk_spawn_count == 2 and hunters() == 2,
			"The selected salvage pair must synchronously pay the two hunters once, including on the bonus transition")
		check(game.contracts.status == ("active" if target_index == 0 else "bonus_offer"),
			"Only the second real salvage F may open the optional bonus decision")
		if target_index == 0:
			assert_read_only_queries(2, true, "selected-salvage-one-source-left")
			var budget: Dictionary = game.contracts.primary_budget()
			check(int(budget.remaining_targets) == 1, "Selected salvage estimates must retain only the actual uncollected second source")
	check(game.contracts.pending_reward.is_empty(), "The synchronous salvage bonus transition must still await return before paying its contract reward")
	var risk_before: int = hunters()
	game.contracts.on_action()
	press(KEY_F)
	check(hunters() == risk_before and game.contracts.risk_spawn_count == 2,
		"Reentrant completion queries and repeated F must not spawn a second salvage risk group")
	await capture("salvage-bonus")
	await close_game()

func frozen_reconciliation_case() -> void:
	if not await boot_day("generator", 2): await close_game(); return
	press(KEY_6)
	var target: Dictionary = game.contracts.targets[0]
	var source: Dictionary = target.source
	put_hero(target.position)
	clear_optional(target.position)
	# Start through the real expedition module to isolate the live source before
	# the controller's next reconciliation; no source state is fabricated.
	check(game.expeditions.interact() and source.state == "active", "The original expedition action must produce a real unobserved active source")
	press(KEY_ESCAPE)
	check(game.phase == "paused", "The actual Escape input must pause the unobserved action")
	var paused := state_snapshot()
	game.contracts.tick(1.0)
	advance(1.0)
	assert_read_only_queries(2, true, "paused-live-selected-source")
	assert_read_only_queries(0, false, "paused-live-other-route")
	check(state_snapshot() == paused and hunters() == 0, "Paused ticks and presentation must neither mark nor spawn the unobserved contract risk")
	press(KEY_ESCAPE)
	game.run.grant("边界验证")
	press(KEY_V)
	check(game.phase == "draft" and game.return_phase == "day", "A queued real card and V input must enter a day-return draft")
	var drafted := state_snapshot()
	game.contracts.tick(1.0)
	advance(1.0)
	assert_read_only_queries(2, true, "draft-live-selected-source")
	check(state_snapshot() == drafted and hunters() == 0, "Draft ticks and presentation must not reconcile or spawn the unobserved risk")
	press(KEY_1)
	check(game.phase == "day", "The actual card input must return from the draft to day")
	game.update_day_contracts(0.0)
	check(game.contracts.progress_started and game.contracts.start_notified and game.contracts.risk_spawned and hunters() == 2,
		"The first resumed authoritative update must reconcile the real source and synchronously create risk")
	game.update_day_contracts(0.0)
	check(hunters() == 2, "Repeated resumed reconciliation must keep the first-action risk one-shot")
	game.contracts.setup(game, 12)
	check(game.contracts.offer_touched.is_empty() and not game.contracts.start_notified and not game.contracts.progress_started and
		not game.contracts.risk_spawned and game.contracts.offer_rejection_reason.is_empty(),
		"Explicit setup must clear the actual recorded touched and notified flags")
	await close_game()

func run() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://build"))
	await generator_case()
	await escort_case()
	await salvage_case()
	await nest_case()
	await unrelated_case()
	for index in 3: await legal_risk_case(index)
	await deadline_case()
	await expired_free_exploration_case()
	await salvage_committed_pair_case()
	await frozen_reconciliation_case()
	var file := FileAccess.open("res://build/contract-prework-evidence.json", FileAccess.WRITE)
	if file: file.store_string(JSON.stringify({"checks": checks, "failures": failures, "cases": evidence}, "\t"))
	print("NIGHTFALL_CONTRACT_PREWORK_", "OK" if failures.is_empty() else "FAILED", " checks=", checks,
		" failures=", failures.size(), " real_f_keys_source_history_risk_once_dusk")
	quit(0 if failures.is_empty() else 1)
